### ISSUE TITLE
S3 Upload Glob pattern not finding files

### ISSUE THREAD

**Issue by spowser** [aws/aws-vsts-tools#7]
I am having trouble getting the S3 upload task to find the files that reside in the following directory:

Source Folder: `\\192.168.1.10\images\upgrade`

Filename Patterns: `*2.0.0.gz*`

The files that reside in that directory have the following names:
```
enabler-2.0.0.gz
enabler-2.0.0.gz-sha256.txt
```

I have tested the glob pattern and it works fine in http://www.globtester.com

However, if you use the default filename pattern: **  it works fine and finds both files.

Any help would be appreciated in solving what's going on here.

**Comment by steveataws** [comment]
The task uses the vsts-task Task's match() method to perform the scan, https://github.com/Microsoft/vsts-task-lib/blob/9a5b51ad05bf83b73bc3c1cdc4dc8ee3704ab8f2/node/task.ts#L1174, with default options. Wondering if we need to be modifying those options (not an expert in this api by any means!).

Anyway, this seems like it should work so marking as bug and will take a look.

**Comment by steveataws** [comment]
I've reported this to Microsoft to see if they have any suggestions, as I can't see any obvious problems.

https://developercommunity.visualstudio.com/content/problem/101263/globbing-pattern-fails-to-select-files-in-taskmatc.html.

**Comment by spowser** [comment]
I tested the Copy Files Task in debug mode and compared that to the output of S3 task in debug mode.  One difference I notice is the patternRoot on the Copy Files Task shows the source directory whereas the S3 task shows 'undefined'.  This may be the root cause.  Pun intended :)

**Comment by spowser** [comment]
I'm looking at line 321 and I think changing

`const matchedPaths = tl.match(allPaths, taskParameters.globExpressions);`
to
`const matchedPaths = tl.match(allPaths, taskParameters.globExpressions, taskParameters.sourceFolder);`

will pass in the pattern root.

**Comment by scrambled2k3** [comment]
I'm seeing this issue as well, I can't get it to recognize anything except **

**Comment by normj** [comment]
Good catch @spowser. I was able to reproduce the error and after making the change you suggested the error went away. I just pushed out version 1.0.6 that has that change.

**Comment by spowser** [comment]
@normj Thanks, I will make the changes to our build process and on the next build report back our findings.

**Comment by normj** [comment]
Closing as I believe this is fixed. Feel free to reopen if you are still having issues.

**Comment by Dzivo** [comment]
I believe this is still an issue 😔. I was trying to do it today but i can not make it work with multiple glob patterns each in a new line. Is this something that is not supported? We need better documentation on this

**Comment by nigerninja** [comment]
This is still an issue in 2023. I'm unable to match any file against the original list using ```**```

**Comment by nigerninja** [comment]
@normj Hi, good evening. Please can you help look into this issue or help refer to who might be able to help out? The S3 upload task as of today v1.13.0. The ** fails to match any files and the debug log shows that all files are recognized from the source folder.
Opened a new issue here [https://github.com/aws/aws-toolkit-azure-devops/issues/519](url)
Thanks.
